name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: alfredo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t alfredo.azurecr.io/huggingface-fastapi:${{ github.sha }}
        docker push alfredo.azurecr.io/huggingface-fastapi:${{ github.sha }}

